### PR TITLE
[SA-4] Create controls

### LINKED ISSUE #7: [SA-4] Create controls
We need to create some controls to manage user input and update state of our game. So we need a virtual joystick (maybe, invisible) and some button to shoot. Please, provide all things related to user input under this ticket.

### PR DESCRIPTION
**Pull request by alexkats**
Fixes #7

### CODE REVIEW

**Review by terradrenor — COMMENTED** [review]
Why do we need so many controllers?

**Review by terradrenor — CHANGES_REQUESTED** [review]
Why do we need so many controllers?

**Comment by alexkats** [comment]
That's because we want to support any type of control, even connected gamepad

**Review by terradrenor — APPROVED** [review]
Cool

**Pull request merged**
